### ISSUE TITLE
ClassCast Exception

### ISSUE THREAD

**Issue by npfitz** [InQBarna/WebIntent#1]
I was having an issue with starting an activity using the plugin. In the logic for the StartActivity method, it was trying to cast my activity to a "DroidGap" Object, which was throwing a Class Cast Exception. I've forked the repo and done removed the references, but I have not been able to throughly test all the other functions. Just thought I should bring this to someones attention.

Cheers,
Nick

**Comment by BraisGabin** [comment]
I merged your commit with my master. Thanks!
