### ISSUE TITLE
New intent not available via onNewIntent

### ISSUE THREAD

**Issue by audaciouscode** [InQBarna/WebIntent#2]
Extras from the new intent are not available via this method's Javascript partner. I've fixed this on my end by setting the activity's intent to the new one at the beginning of the method:

```
public void onNewIntent(Intent intent) {
    // Begin fix.
    ((DroidGap) this.cordova.getActivity()).setIntent(intent);
    // End fix.

    if (this.onNewIntentCallback != null) {
        PluginResult result = new PluginResult(PluginResult.Status.OK, intent.getDataString());
        result.setKeepCallback(true);
        this.success(result, this.onNewIntentCallback);
    }
}
```

I'm working on the 2.9 stack, so I'm sure that an equivalent fix can be made for the 3.x branches. I needed to do this so that I could pass data back to the Cordova activity that wasn't readily encoded in a data URI. Once I did this, I could use extras as well.

**Comment by audaciouscode** [comment]
Here's the HTML that I am using to call your plugin:

https://github.com/nupmmarkbegale/Purple-Robot-Manager/blob/master/PhoneGapTester/assets/www/index.html

We have another app (Purple Robot) that exposes some additional functionality via a Javascript interface. Traditionally, this has been exposed via a built-in HTTP server to Cordova apps, but this needed to be exposed via an intent-driven mechanism when we discovered that some Android manufacturers shut down the loopback interface in situations we did not expect.

**Comment by guidokessels** [comment]
This worked for me: `this.cordova.getActivity().setIntent(intent);`. Thanks a ton, without this line the new intent was not available after app resume.

@BraisGabin Could you look at this and merge a fix in the plugin?

**Comment by adewaleafolabi** [comment]
@guidokessels Please could you provide a complete listing of how you achieved this? I've been having problems retrieving intent data while running the application in singleInstace/SingleTop/singleTask mode. Thanks

**Comment by JohnMcLear** [comment]
Confirmed this needs a patch. @guidokessels can you please submit a PR w/ the patch to WebIntent.java ? Thanks

PS I tried adding  `this.cordova.getActivity()).setIntent(intent);` but it didn't work for me

I get the intent event but the intent value is nothing and doing hasExtra returns false.

**Comment by ericpeters0n** [comment]
+1
Working fork? Currently getting the same intent data each resume...

**Comment by BraisGabin** [comment]
Fixed
