### ISSUE TITLE
Javascript filename mismatch

### ISSUE THREAD

**Issue by paulthiggins** [InQBarna/WebIntent#3]
I think the javascript filename is incorrect - it is "webintent.js" in the plugin.xml and "webIntent.js" (i.e. a capital "I") in the actual source folder, this causes a "NOENT" error when I try to install it using the cordova command line. I think it's just a matter of changing the name in one place (so that matches the documentation), but I'm not much of a github person yet. Here is how to recreate the error (on Linux):

```
$cordova create test
$cd test
$cordova platform add android
$cordova plugin add https://github.com/InQBarna/WebIntent.git
Fetching plugin from "https://github.com/InQBarna/WebIntent.git"...
Starting installation of "com.borismus.webintent" for android
Preparing android project
{ [Error: ENOENT, no such file or directory '/home/paul/cordova/test/plugins/com.borismus.webintent/www/webintent.js']
  errno: 34,
  code: 'ENOENT',
  path: '/home/paul/cordova/test/plugins/com.borismus.webintent/www/webintent.js',
  syscall: 'open' }
```

**Comment by BraisGabin** [comment]
zsh hid me this. Thanks!

**Comment by paulthiggins** [comment]
Works a treat, thanks.
