### ISSUE TITLE
 Catch an incoming intent from within a resumed application

### ISSUE THREAD

**Issue by cosmopolit** [InQBarna/WebIntent#7]
Thank you for your updated version. I wonder how i can catch the Intent if a running application is brought back to front on resume. I use the following listener: document.addEventListener("resume", refreshIntentReq, false); But when i try to catch the intent from within refreshIntentReq, the shared intent is empty.

Is it possible to catch an incoming intent from within a resumed application?

Thank You!

**Comment by JohnMcLear** [comment]
@cosmopolit this is catching me out too but it's not working..  Did you manage to get a fix?

**Comment by JohnMcLear** [comment]
I think this is related to https://github.com/InQBarna/WebIntent/issues/2

**Comment by BraisGabin** [comment]
Dup
